version: 0.2

phases:
  install:
    commands:
      - npm i -g yarn
      - yarn
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - yarn build
      - echo '["https://compile.duino.app"]' > dist/servers.json
artifacts:
  files:
    - '**/*'
  base-directory: dist